### ISSUE TITLE
run mklmulticlass.m

### ISSUE THREAD

**Issue by lanyuelvyun** [yage99/simplemkl#1]
When i run mklmulticlass.m, the following error occurred: 
Input strings must have one row.

Error in vectorize (line 19)
    v = strrep(v,'*','.*');

Error in build_efficientK (line 24)
        Kse.data(:,j) = vectorize(Ks(:,:,j));

Error in mklmulticlass (line 27)
            K = build_efficientK(K);

Error in exmklmulticlass (line 71)
[beta,w,w0,pos,nbsv,SigmaH,obj] = mklmulticlass(K,yapp,C,nbclass,options,verbose);

Do you know why? I run it on matlab R2012a.

**Comment by yage99** [comment]
Maybe you could provide more information about this error. For example, you can provide a sample of your dataset that cause this error.

**Comment by lanyuelvyun** [comment]
非常抱歉，我写错了。我是在运行exmklmulticlass.m的时候出现了上述错误。exmklmulticlass.m里面自动生成了示例数据，我就用的这个示例数据，没有用自己的数据。运行的时候，就一直出现上面的错误，请问，你知道是什么原因吗？

**Comment by yage99** [comment]
I think you should compile ‘vectorize.c’ to mex manually in your Matlab.
Matlab has an internal function defined as ‘vectorize’, which is totally different from the ‘vectorize’ function in simpleMKL package. Your Matlab doesn’t load the contained pre-compiled vectorize mex file automatically and call the internal ‘vectorize’ function wrongly. This means you may have to compile it by yourself.

2017年7月12日 +0800 17:45 lanyuelvyun <notifications@github.com>，写道：

**Comment by yage99** [comment]
This is not a bug of this package. One should compile c source file manually.

**Comment by lanyuelvyun** [comment]
Very appreciate of your patience.
